## Dynamic Configuration

http:
  routers:
    # Frontend router
    app-frontend:
      rule: "PathPrefix(`/`)"
      service: "app-frontend"
      entryPoints:
        - web
      priority: 1
    
    # API router
    app-backend:
      rule: "PathPrefix(`/api`)"
      service: "app-backend"
      entryPoints:
        - web
      priority: 10

  services:
    # Frontend service
    app-frontend:
      loadBalancer:
        servers:
          - url: "http://app:80"
    
    # Backend service
    app-backend:
      loadBalancer:
        servers:
          - url: "http://app:5000"
